version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gosec
    - govet
    - ineffassign
    - nlreturn
    - noctx
    - revive
    - staticcheck
    - tagliatelle
    - unparam
    - whitespace
  settings:
    revive:
      rules:
        - name: duplicated-imports
          severity: warning
          disabled: false
    tagliatelle:
      case:
        rules:
          json: camel
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: .*mock.*
    paths:
      - \.pb\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - third_party$
      - builtin$
      - examples$
